# Generated by Django 5.1.3 on 2025-01-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
    ]
